package com.hapms.ai;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import java.util.HashMap;
import java.util.Map;

@SpringBootApplication
@RestController
public class AiServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(AiServiceApplication.class, args);
    }

    @PostMapping("/api/v1/ai/triage")
    public ResponseEntity<Map<String, Object>> triage(@RequestBody Map<String, String> request) {
        String symptoms = request.get("symptoms");
        Map<String, Object> response = new HashMap<>();
        response.put("symptoms", symptoms);

        if (symptoms.toLowerCase().contains("chest pain") || symptoms.toLowerCase().contains("shortness of breath")) {
            response.put("urgency", "CRITICAL");
            response.put("specialty", "Cardiology");
            response.put("recommendation", "CRITICAL: Please seek emergency medical care immediately at the nearest ER.");
        } else if (symptoms.toLowerCase().contains("headache") || symptoms.toLowerCase().contains("migraine")) {
            response.put("urgency", "MODERATE");
            response.put("specialty", "Neurology");
            response.put("recommendation", "MODERATE: Persistent headaches require consultation. We suggest booking an appointment with a Neurologist.");
        } else {
            response.put("urgency", "LOW");
            response.put("specialty", "General Medicine");
            response.put("recommendation", "LOW: General check-up recommended. Please book a standard consultation.");
        }

        response.put("disclaimer", "Disclaimer: This triage output is generated by AI for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment.");
        return ResponseEntity.ok(response);
    }

    @PostMapping("/api/v1/ai/drug-interaction")
    public ResponseEntity<Map<String, Object>> checkDrugInteraction(@RequestBody Map<String, Object> request) {
        String medications = (String) request.get("medications");
        Map<String, Object> response = new HashMap<>();
        response.put("medications", medications);

        if (medications.toLowerCase().contains("ibuprofen") && medications.toLowerCase().contains("aspirin")) {
            response.put("status", "WARNING");
            response.put("severity", "MODERATE");
            response.put("message", "Concomitant use of Ibuprofen and Aspirin can increase the risk of gastrointestinal bleeding. Please monitor or consult your physician.");
        } else {
            response.put("status", "CLEAR");
            response.put("severity", "NONE");
            response.put("message", "No significant interactions detected.");
        }
        return ResponseEntity.ok(response);
    }
}
